version: "3.8"
services:
  db:
    container_name: mysql
    build: ./db
    image: trio-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: flask-db
    volumes:
    - type: volume
      source: trio-task-db
      target: /var/lib/mysql
  flask-app:
    build: ./flask-app
    image: trio-task
    container_name: trio-task-flask-app
      
    
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  trio-task-db:
